### ISSUE TITLE
Add "Video" by The Processing Foundation to README.md

### ISSUE THREAD

**Issue by jeremydouglass** [diwi/PixelFlow#1]
Currently, the list of "Dependencies, to run the examples" lists
-  processing-video-library, by Andres Colubri   https://processing.org/reference/libraries/video/index.html

I'm not sure if Andres was once the original author or if this is a confusion with Syphon, but for people installing dependencies via Processing 3.2.1 Contribution Manager, they won't be able to find "processing-video-library" in their Libraries tab. Instead (or in addition), the dependency should be listed as:
-  Video, by The Processing Foundation.

**Comment by diwi** [comment]
thx for the hint! -> done.
