### ISSUE TITLE
Import Processing

### ISSUE THREAD

**Issue by knupel** [diwi/PixelFlow#15]
May be is not necessary to write by default, 
```
import processing.core.*;
import processing.opengl.PGraphics2D;
```
because when you open the example in Processing, Processing return an error message. 

Plus may be remove all the part `private` `public`... of course that depend if you want a novice or advance users :)

**Comment by diwi** [comment]
so whats the error message?

**Comment by knupel** [comment]
This one for each line when it's ask to import a Processing stuff, already use in the Processing IDE. I don't understand why the window talk about `Touchatag`, but after comment the line where Processing is imported that's work fine ; the only stuff of Processing must be imported it's a `import processing.video.Capture;` because it's not included in the IDE

![capture d ecran 2017-07-11 a 14 21 52](https://user-images.githubusercontent.com/3332269/28068102-527828e2-6644-11e7-8e94-1a20f6e51557.png)

**Comment by diwi** [comment]
thats actually a problem with the touchatag library.

you should remove the following file:
touchatag/library/core.jar

no library is supposed to come with processings core.jar in the library folder.

**Comment by diwi** [comment]
besides that, i am not sure if this library is compatible with processing 3? or is it?

**Comment by knupel** [comment]
I talk too much, too fast. You're true that's work perfectly know. It's not necessary to comment the line where processing stuff is imported. Thx.

**Comment by diwi** [comment]
The main reason why you find those imports and all these private/public declarations is that i develop these examples in the eclipse-IDE, and just copy the code to the PDE and then change only the necessary stuff to make the examples work.

I am too lazy to remove all the private/public modifiers in all the 60+ examples.

**Comment by jeffThompson** [comment]
Just FYI this is still an issue and I'm sure would be confusing to new users (took me a minute to figure it out and I've been using Processing for years). Maybe a cleanup script to remove those imports before committing the library?

**Comment by hamoid** [comment]
This command removed recursively those `import processing...` when I tried on Linux:

    find . -type f -name "*.java" -exec bash -c 'sed -i "/^import processing/ d" {}' \;

Based on https://stackoverflow.com/a/9709296 maybe adding `''` after `-i` is required on mac, not sure.

It searches recursively for *.java files and then discards lines that start with `import processing`.
