### ISSUE TITLE
Problem with Javax in Processing IDE

### ISSUE THREAD

**Issue by knupel** [diwi/PixelFlow#16]
When you want run few sketches who used Javax, it's necessary to import it, but how it's possible in Processing IDE ? I find no track to do it...

**Comment by diwi** [comment]
pixelflow is a library that heavily depends on OpenGL/GLSL. Thats why all examples use PGraphicsOpenGL (P2D or P3D) as framebuffers.

**Comment by knupel** [comment]
Maybe it's a bug in my mind, because now there is no problem to import `javax.*`stuff. Sorry for disturbing.

**Comment by diwi** [comment]
you're not disturbing at all, dont worry.

Well, you can use javax in your sketches, but those framebuffers cant be used for the majority of the pixelflow operations.
