### ISSUE TITLE
FlowField particles not working

### ISSUE THREAD

**Issue by eccoscreen** [diwi/PixelFlow#21]
Hey one of the earlier updates to this broke the flowfield particles on MacOS. Nothing shows up in the examples. Here's the error i get in Processing:

`null (/com/thomasdiewald/pixelflow/glsl/FlowFieldParticles/particles_display_points.glsl)
ERROR: 0:59: '{' : syntax error: syntax error`

Seems like vec4 uniform arrays aren't compatible on MacOS

**Comment by diwi** [comment]
Thx for the report!
will be fixed in the next release.
