### ISSUE TITLE
OpticalFlow_MovieFluid not working

### ISSUE THREAD

**Issue by lanigoa** [diwi/PixelFlow#23]
hey,

I have a problem with OpticalFlow_MovieFluid, after pressing Run in Processing, a new window opens and is immediately closed. This happens on my windows7 64bit computer. Every other example in optical flow works fine. The console says:

[-] PixelFlow v1.20 - www.thomasdiewald.com

[-] DEVICE ... AMD Radeon R9 200 / HD 7900 Series
[-] GLSL ..... #version 450 core / 4.50.0
[-] GL ....... 4.5 (Core profile, arb, compat[ES2, ES3, ES31], FBO, hardware) - 4.5.13506 Core Profile Context 23.20.15002.11

And I get one Error: 

The method addTemperatureTexture(DwFluid2D fluid, DwOpticalFlow opticalflow) from the type OpticalFlow_MovieFluid.MyFluidData is never used locally.

I have updated my graphics driver and I'm using PixelFlow 1.20. In the original code I changed your pulp Fiction video with my own.

Hope this helps

**Comment by diwi** [comment]
sounds like the movie-file is not found. 
Make sure the relative or absolute path to the file is correct.

Just in case, use one of the basic example from the video-library to load your file:
https://processing.org/reference/libraries/video/Movie.html

If that works, it should also work in the optical-flow example.

**Comment by lanigoa** [comment]
Just tried it with the absolute path and it works now.

Thank you for your fast reply
