### ISSUE TITLE
Read optical flow vectors

### ISSUE THREAD

**Issue by DasPez** [diwi/PixelFlow#4]
Hi, 
I want to calculate the average optical flow in an area of my camera feed. 
Is it possible to access the velocity vector of a certain pixel?
opticalflow.getVelocity() throws a null pointer exeption when I try to print one element of the float[] to console.

**Comment by diwi** [comment]
I am unable to reproduce the nullpointer exception. Can you post a short example? 

[getVelocity(float[] data_F4)](https://github.com/diwi/PixelFlow/blob/master/src/com/thomasdiewald/pixelflow/java/imageprocessing/DwOpticalFlow.java#L215) should return a valid array in any case.
