### ISSUE TITLE
Experiencing glitches in OpticalFlow examples

### ISSUE THREAD

**Issue by AmnonOwed** [diwi/PixelFlow#7]
Hey Thomas,

Excellent work on your library! 👍

I've been trying out all the examples, looking good! 😄

I ran into some glitches in the OpticalFlow examples, leading to rectangles in the output (see screenshot below) and eventually preventing the sketch from functioning at all (the webcam image showed, but no optical flow). Luckily updating the drivers for my NVIDIA GeForce GTX 770 solved the problem and now everything is running smoothly!

But for future reference I thought I'd share this anyway, so if someone else runs into similar issues they know how to solve it: make sure to update your drivers!

![glitch](https://cloud.githubusercontent.com/assets/4075846/24324983/713e82ca-1190-11e7-97ff-2beee5c55be5.jpg)

**Comment by diwi** [comment]
Hi Amnon,

Thank you for the feedback and the screenshot!

I've had seen similar artifacts myself now and then during developing the library. Updating the driver is indeed the first and easiest step to try to get rid of these ... Anything else needs painful debugging :)


Thx, Thomas
