### ISSUE TITLE
Optical Flow examples not working on new Macbook Pro

### ISSUE THREAD

**Issue by alexfgreen** [diwi/PixelFlow#8]
seems to quietly crash the rendering, the sketch seems to keep running but no pixelflow visible. 

PixelFlow v0.51  -  http://www.thomasdiewald.com
-------------------------------------------------------------------
    OPENGL_VENDOR:         ATI Technologies Inc.
    OPENGL_RENDERER:       AMD Radeon Pro 460 OpenGL Engine
    OPENGL_VERSION:        4.1 ATI-1.50.38
    GLSLVersionString:     #version 410 core
    GLSLVersionNumber:     4.10.0
    GLVersion:             4.1 (Core profile, arb, compat[ES2, ES3], FBO, hardware) - 4.1 ATI-1.50.38
    GLVendorVersionNumber: 1.50.38 (ATI-1.50.38)
-------------------------------------------------------------------

**Comment by diwi** [comment]
thx for report!
not sure though if this can be fixed since i cant reproduce the error on my system. 
Does this happen on the "OpticalFlow_Basic" example (just so i can cancel out any additional features like webcam capturing etc...)?

**Comment by diwi** [comment]
btw, in case you are refering to the OpticalFlow_MovieFluid example.

The library doesnt come with the movie file to keep the filesize of the distribution small, ... this is why this one isnt executing. Though, you can find the original file i am using in the github repository here: 
https://github.com/diwi/PixelFlow/tree/master/examples/data

But of course you can test this example with any movie file you like.

**Comment by diwi** [comment]
another hint is to update the graphics card driver.

AmnonOwed pointed that out a while ago: https://github.com/diwi/PixelFlow/issues/7
