### ISSUE TITLE
Skylight_Poisson Example not compiling

### ISSUE THREAD

**Issue by alexfgreen** [diwi/PixelFlow#9]
PixelFlow v0.51  -  http://www.thomasdiewald.com
-------------------------------------------------------------------
    OPENGL_VENDOR:         ATI Technologies Inc.
    OPENGL_RENDERER:       AMD Radeon Pro 460 OpenGL Engine
    OPENGL_VERSION:        4.1 ATI-1.50.38
    GLSLVersionString:     #version 410 core
    GLSLVersionNumber:     4.10.0
    GLVersion:             4.1 (Core profile, arb, compat[ES2, ES3], FBO, hardware) - 4.1 ATI-1.50.38
    GLVendorVersionNumber: 1.50.38 (ATI-1.50.38)
-------------------------------------------------------------------
poisson samples: 181
null (/com/thomasdiewald/pixelflow/glsl/antialiasing/SMAA/smaa1_edges.vert)
ERROR: 0:306: '' : syntax error: incorrect preprocessor directive
ERROR: 0:306: '' : syntax error: unexpected tokens following #if preprocessor directive - expected a newline
ERROR: 0:510: '' : syntax error: incorrect preprocessor directive
ERROR: 0:510: '' : syntax error: unexpected tokens following #if preprocessor directive - expected a newline
ERROR: 0:524: '' : syntax error: incorrect preprocessor directive
ERROR: 0:524: '' : syntax error: unexpected tokens following #if preprocessor directive - expected a newline
ERROR: 0:525: 'SamplerState' : syntax error: syntax error
RROR: 0:525: 'SamplerState' : syntax error: syntax error

ERROR: One or more attached shaders not successfully compiled
/com/thomasdiewald/pixelflow/glsl/antialiasing/SMAA/smaa1_edges.vert//com/thomasdiewald/pixelflow/glsl/antialiasing/SMAA/smaa1_edges.frag: uniform location "wh_rcp" = -1

null (/com/thomasdiewald/pixelflow/glsl/antialiasing/SMAA/smaa2_blend.frag)
ERROR: 0:306: '' : syntax error: incorrect preprocessor directive
ERROR: 0:306: '' : syntax error: unexpected tokens following #if preprocessor directive - expected a newline
ERROR: 0:510: '' : syntax error: incorrect preprocessor directive
ERROR: 0:510: '' : syntax error: unexpected tokens following #if preprocessor directive - expected a newline
ERROR: 0:524: '' : syntax error: incorrect preprocessor directive
ERROR: 0:524: '' : syntax error: unexpected tokens following #if preprocessor directive - expected a newline
ERROR: 0:525: 'SamplerState' : syntax error: syntax error

**Comment by diwi** [comment]
i have seen this issue before on another system. apparently some compiler have problems with the SMAA antialiasing shader ... algouth i used the original source file from here
http://www.iryoku.com/smaa/

It should work to just replace SMAA with FXAA. or not use any AntiAliasing at all.  I will take care of it in the next release.

**Comment by alexfgreen** [comment]
awesome-- do you have any suggestions of places to look for examples code
for FXAA?

**Comment by kasperkamperman** [comment]
I've ported a while ago an FXAA shader found on ShaderToy to Processing. I also had problems with SMAA. 

https://gist.github.com/kasperkamperman/71b67f91445fc5993f90573c0e48a03e

I hope it helps in someway (I'm not an expert in shaders).

**Comment by diwi** [comment]
PixelFlow already has support for FXAA.

source: 
https://github.com/diwi/PixelFlow/tree/master/src/com/thomasdiewald/pixelflow/java/antialiasing
reference: 
http://thomasdiewald.com/processing/libraries/pixelflow/reference/com/thomasdiewald/pixelflow/java/antialiasing/FXAA/FXAA.html

the AntiAliasing example (https://github.com/diwi/PixelFlow/blob/master/examples/AntiAliasing/AntiAliasing.java) does a comparison of all AA modes and demonstrates how to use them.



The reason i picked SMAA for the skylight examples is, that is looks a bit better imo than FXAA.

Anyways, i'll do a new release later today with updated library examples.

**Comment by diwi** [comment]
updated release v0.52 (22) https://github.com/diwi/PixelFlow/releases

1) skylight examples for SMAA and alternatively FXAA.

2) tried to fix the SMAA issues which seem to occur on certain platforms.
I really would appreciate if someone could run the SMAA examples and post the log here if there are still compile errors. thx!

**Comment by kasperkamperman** [comment]
I've tried the Anti-Aliasing example. 
SMAA works now. 
However GBAA breaks with the following error (I had to type it over manually): 

```Cannot compile fragment shader:ERROR: 0.26:bvec3 can't be in in the fragment shaderERROR: 0:36: Use of undeclared identifier 'FragLnERROR: 0:37:Use of undeclared identifier 'Fragln'ERROR: 0:39: Use of...```
```

PixelFlow v0.52  -  http://www.thomasdiewald.com
-------------------------------------------------------------------
    OPENGL_VENDOR:         Intel
    OPENGL_RENDERER:       Intel(R) Iris(TM) Graphics 6100
    OPENGL_VERSION:        4.1 INTEL-10.6.33
    GLSLVersionString:     #version 410 core
    GLSLVersionNumber:     4.10.0
    GLVersion:             4.1 (Core profile, arb, compat[ES2, ES3], FBO, hardware) - 4.1 INTEL-10.6.33
    GLVendorVersionNumber: 10.6.33 (INTEL-10.6.33)
-------------------------------------------------------------------
```

**Comment by diwi** [comment]
thx a lot!

GBAA is fixed now too (i hope, since my compiler didnt give me any of those errors).

**Comment by alexfgreen** [comment]
awesome! thanks!
